CFLAGS = -DITERATIONS=100 -I.

ROM_SOURCES=../rom.s
DRAM_SOURCES=core_list_join.cpp core_main.cpp core_matrix.cpp core_state.cpp core_util.cpp core_portme.cpp ee_printf.cpp ../uart.cpp ../sim_utils.cpp ../event_counters.cpp

include ../common.mak

